app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => 'web'], function () {
    Route::auth();
    //Home / Promotional info
    Route::get('/', ['uses' => 'HomeController@index', 'as' => 'home']);
    Route::resource('promoInfo', 'HomeController');

    //Portfolio items
	Route::get('portfolio', ['uses' => 'PortfolioController@index', 'as' => 'portfolio']);
	Route::resource('portfolioItem', 'PortfolioController');

	//Accolades
	Route::get('accolades', ['uses' => 'AccoladesController@index', 'as' => 'accolades']);
	Route::resource('accolade', 'AccoladesController');

	//History
	Route::get('history', ['uses' => 'HistoryController@index', 'as' => 'history']);
	Route::resource('historyItem', 'HistoryController');

	Route::resource('contact', 'ContactController');
    // Route::get('/', 'HomeController@index');
});

resources/views/accolades.blade.php
@extends('layouts.master')

@section('content')
    @if(Session::has('feedback'))
        <div class="alert alert-info center">
            {{Session::get('feedback')}}
        </div>
    @endif
    @foreach($accolades as $accolade)
    <div class="page-header main-info">
        <h3 class="strong">{{$accolade->title}}<br><small>{{$accolade->info}}</small></h3>
        @if (!empty($accolade->url))
            <div class="list-group">
              <a href="{{$accolade->url}}" target="_blank" class="list-group-item">
                <p class="list-group-item-text strong">
                    <span class="glyphicon glyphicon-new-window link" aria-hidden="true"></span>
                    {{$accolade->title}}
                </p>
              </a>
            </div>
        @endif
    </div>
    @if (Auth::check())
        <div class="main-info center">
            <a type="button" class="btn btn-info btn-md" title="Edit" href="{{route('accolade.edit',$accolade->id)}}">
                <span class="glyphicon glyphicon-edit"></span>
            </a>
            {!! Form::open(['url' => ['accolade', $accolade->id], 'method' => 'delete', 'style' => 'display:inline;']) !!}
                <button id="removeReg" type="submit" class="btn btn-danger btn-md" title="Remove">
                    <span class="glyphicon glyphicon-remove"></span>
                </button>
            {!! Form::close() !!}
        </div>
    @endif
    @endforeach
    @if (Auth::check())
        <div class="center main-info">
            <a class="btn btn-primary" href="{{route('accolade.create')}}">Add accolade</a>
        </div>
    @endif
@endsection

resources/views/history.blade.php
@extends('layouts.master')

@section('content')
    @if(Session::has('feedback'))
        <div class="alert alert-info center">
            {{Session::get('feedback')}}
        </div>
    @endif
    @foreach($historyItems as $item)
    <div class="page-header main-info">
        <h3 class="strong">{{$item->timeframe}}<br><small class="info">{{$item->company}}</small></h3>
        <h6>{{$item->info}}</h6>
        @if(!empty($item->url))
            <div class="list-group">
              <a href="{{$item->url}}" target="_blank" class="list-group-item">
                <p class="list-group-item-text strong" >
                    <span class="glyphicon glyphicon-new-window link" aria-hidden="true"></span>
                    {{$item->company}}
                </p>
              </a>
            </div>
        @endif
        @if (Auth::check())
            <div class="main-info center">
                <a type="button" class="btn btn-info btn-md" title="Edit" href="{{route('historyItem.edit',$item->id)}}">
                    <span class="glyphicon glyphicon-edit"></span>
                </a>
                {!! Form::open(['url' => ['historyItem', $item->id], 'method' => 'delete', 'style' => 'display:inline;']) !!}
                    <button id="removeReg" type="submit" class="btn btn-danger btn-md" title="Remove">
                        <span class="glyphicon glyphicon-remove"></span>
                    </button>
                {!! Form::close() !!}
            </div>
        @endif
    </div>
    @endforeach
    @if (Auth::check())
        <div class="center main-info">
            <a class="btn btn-primary" href="{{route('historyItem.create')}}">Add historic item</a>
        </div>
    @endif
@endsection

resources/views/home.blade.php
@extends('layouts.master')

@section('content')
<div class="page-header center">
    @if(Session::has('feedback'))
        <div class="alert alert-info">
            {{Session::get('feedback')}}
        </div>
    @endif
    @if (!empty($info))
        <div class="profile-header-container">   
            <div class="profile-header-img">
                <img class="img-circle" src="{{ asset($info->image) }}" />
                <!-- badge -->
     <!--            <div class="rank-label-container">
                    <span class="label label-default rank-label">100 puntos</span>
                </div> -->
            </div>
        </div>
        <h1><strong>{{$info->company_name}}</strong><br><small>{{$info->sub_heading}}</small></h1>
    @endif
</div>
<div class="center main-info">
    @if (!empty($info))
        <h5>{{$info->info}}</h5>
    @endif
    @if (Auth::check() && !empty($info))
        <a class="btn btn-primary" href="{{route('promoInfo.edit',$info->id)}}">Edit promo info</a>
    @elseif (Auth::check() && empty($info))
        <a class="btn btn-primary" href="{{route('promoInfo.create')}}">Add promo info</a>
    @elseif (empty($info))
        <h4> Login to add promo info </h4>
    @endif
</div>
@endsection

resources/views/portfolio.blade.php
@extends('layouts.master')

@section('content')
    @if(Session::has('feedback'))
        <div class="alert alert-info center">
            {{Session::get('feedback')}}
        </div>
    @endif
    @foreach($portfolioItems as $item)
    <div class="panel panel-default">
        <div class="panel-heading center"><h4 class="strong">{{$item->title}}</h4></div>
        <div class="panel-body">
            @if(!empty($item->link))
                <div class="list-group">
                  <a href="{{$item->link}}" target="_blank" class="list-group-item">
                    <p class="list-group-item-text strong">
                        <span class="glyphicon glyphicon-new-window link" aria-hidden="true" ></span>
                        {{$item->title}}
                    </p>
                  </a>
                </div>
            @endif
            <h5>{{$item->info}}</h5>
            <p class="info"><strong>Created with:</strong></p>
            <ul>
                @foreach($item->frameworks as $framework)
                <li class="info" style="font-weight:bold; font-family: Lucida Console;">{{$framework->framework->name}}</li>
                @endforeach
            </ul>
            <div class="row" style="display:flex; flex-wrap: wrap;">
                @foreach($item->images as $image)
                <div class="col-xs-6 col-md-3">
                    <a href="{{asset($image->url)}}" rel="prettyPhoto" class="thumbnail">
                        <img src="{{asset($image->url)}}">
                    </a>
                </div>
                @endforeach
            </div>
        </div>
        @if (Auth::check())
            <div class="main-info center">
                <a type="button" class="btn btn-info btn-md" title="Edit" href="{{route('portfolioItem.edit',$item->id)}}">
                    <span class="glyphicon glyphicon-edit"></span>
                </a>
                {!! Form::open(['url' => ['portfolioItem', $item->id], 'method' => 'delete', 'style' => 'display:inline;']) !!}
                    <button id="removeReg" type="submit" class="btn btn-danger btn-md" title="Remove">
                        <span class="glyphicon glyphicon-remove"></span>
                    </button>
                {!! Form::close() !!}
            </div>
        @endif
    </div>
    @endforeach
    @if (Auth::check())
        <div class="center main-info">
            <a class="btn btn-primary" href="{{route('portfolioItem.create')}}">Add portfolio item</a>
        </div>
    @endif
@endsection